# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_firstname', models.CharField(max_length=64)),
                ('person_lastname', models.CharField(max_length=64)),
                ('person_dob', models.DateTimeField(auto_now_add=True)),
                ('person_zip', models.CharField(max_length=16)),
            ],
        ),
    ]
